spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog01?serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.hut.suaijun.bean

